check_http: add --status
monitoring-plugins/monitoring-plugins pull request #1616
Opened 2020-01-08 20:17 UTC by Al2Klimov

2020-01-08 20:18 UTC, Al2Klimov commented
```
➜  monitoring-plugins git:(feature/http-status) plugins/check_http -H 127.0.0.1 -p 8080 -u /404
HTTP WARNING: HTTP/1.1 404 Not Found - 303 bytes in 0,004 second response time |time=0,003679s;;;0,000000;10,000000 size=303B;;;0
➜  monitoring-plugins git:(feature/http-status) plugins/check_http -H 127.0.0.1 -p 8080 -u /404 --status 404
HTTP OK: HTTP/1.1 404 Not Found - 303 bytes in 0,004 second response time |time=0,004444s;;;0,000000;10,000000 size=303B;;;0
➜  monitoring-plugins git:(feature/http-status) plugins/check_http -H 127.0.0.1 -p 8080 -u /404 --status 404 --status 403
HTTP OK: HTTP/1.1 404 Not Found - 303 bytes in 0,007 second response time |time=0,007177s;;;0,000000;10,000000 size=303B;;;0
➜  monitoring-plugins git:(feature/http-status)
```

2020-01-08 20:20 UTC, Al2Klimov commented
Useful for monitoring e.g. 401s where they're required.

2020-01-08 20:49 UTC, sni commented
Why don't you use `-e`?

2020-01-08 21:40 UTC, Al2Klimov commented
1. IMAO a bit cheaty
2. IMAO the status check should not silently disable the (default) check for "HTTP/1."

2021-11-01 16:48 UTC, RincewindsHat requested changes

2021-11-01 16:48 UTC, RincewindsHat commented on plugins/check_http.c
> + 1st bit for 100, 2nd for 101, etc.. None set means defaults.
Why?

2021-11-01 16:48 UTC, RincewindsHat commented on plugins/check_http.c
> +  status_expect[idx / 64u] |= 1u << (idx % 64u);
Please add a comment explaining what this does or rewrite it in an understandable manner.

2021-11-01 16:48 UTC, RincewindsHat commented on plugins/check_http.c
> +  return !!(status_expect[idx / 64u] & (1u << (idx % 64u)));
Please add a comment explaining what this does or rewrite it in an understandable manner.

2022-11-14 00:01 UTC, RincewindsHat commented
Closing this. Pls reopen, if continuation is wished for

2022-11-14 00:01 UTC, closed without merging