check_mysql: Add a -N slave_name option
monitoring-plugins/monitoring-plugins pull request #1716
Opened 2021-10-29 09:32 UTC by GerMalaz

Checks for MariaDB in server_info on deciding to use `show slave 'slave_name' status` (if matches) or `show slave status for channel '%s'` (if it doesn't match).

INCOMPATIBILITY:
      When more than one slave is present, the first one returned was checked.
      Now it fails in that case, if the -N/--slave-name option is not used.

2026-09-09 07:32 UTC, RincewindsHat commented
Sorry for not responding.
What does this do/help/improve?

2026-09-09 11:43 UTC, GerMalaz commented
If you have more than one replica, you can name all of them, and check them separately.

2026-09-09 12:19 UTC, GerMalaz commented
Iv recently updated the patch for this.
there have been changes in this area that affect it.

2026-09-09 13:10 UTC, RincewindsHat commented
Yes, sorry about that. The logic changed a bit due to refactoring and the change in naming conventions (`slave` -> `replica`).
I might give it a go to reimplement the idea or, if you are willing, you could give it a try yourself.

2026-09-10 16:08 UTC, GerMalaz commented
Not a problem.
As I said, I already did.
Used the (now) available checks for mysql|mariadb to assign the different syntax if a named replica is requested.

2026-09-11 16:32 UTC, GerMalaz commented
Ooops, didn't mean to close this, so I reopened it.
Updated for current code.
Note there is also a bugfix (replicas were always (reportedly) unavailable)

2026-09-12 09:59 UTC, RincewindsHat requested changes
Also running `clang-format` would be nice to have the same style everywhere

2026-09-12 09:59 UTC, RincewindsHat commented on plugins/check_mysql.c
> +static char *replica_query = NULL;
Is it necessary for these variables to be global? If possible they should only be available where needed.

2026-09-12 09:59 UTC, RincewindsHat commented on plugins/check_mysql.c
> +static int num_slaves = 0;
That should be `num_replicas`?

2026-09-12 22:44 UTC, GerMalaz commented on plugins/check_mysql.c
> +static int num_slaves = 0;
Resolved in https://github.com/monitoring-plugins/monitoring-plugins/pull/1716/commits/0b819588af4d7188079264e2e329c2ab5b839271

2026-09-12 22:45 UTC, GerMalaz commented on plugins/check_mysql.c
> +static char *replica_query = NULL;
Addressed in https://github.com/monitoring-plugins/monitoring-plugins/pull/1716/commits/462a20a341dba51e15429aef12d5e4f92eec7316

2026-09-12 22:51 UTC, GerMalaz commented
> Also running `clang-format` would be nice to have the same style everywhere

Tried this (without parameters), and affected code beyond the scope of this PR.

2026-09-16 11:24 UTC, RincewindsHat approved these changes
Looks good :-)

Thank you for the contribution and the patience.

2026-09-16 11:24 UTC, merged

2026-09-17 12:28 UTC, c-kr commented
@RincewindsHat 

This fails to build on Arch Linux with the default build flag `-Werror=format-security`

```
check_mysql.c: In function ‘main’:
check_mysql.c:338:46: error: format not a string literal and no format arguments [-Werror=format-security]
  338 |                                         :  _("too many replicas defined, please provide a replica name as an argument")
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common.h:195:27: note: in definition of macro ‘_’
  195 | #define _(String) gettext(String)
      |                           ^~~~~~

```

Minimal fix (by LLM, tested locally):

```diff
-                       mopl_utils_xasprintf(&sc_replica.output,
+                       mopl_utils_xasprintf(&sc_replica.output, "%s",

2026-09-17 16:10 UTC, GerMalaz commented
I see, sorry.
Somehow this didn't show up on my environment (debian forky/sid), should have.

2026-09-17 19:20 UTC, RincewindsHat commented
fixed it

2026-09-17 19:46 UTC, GerMalaz commented
Thanks!