check_by_ssh: Add "-U" flag (#1123).
monitoring-plugins/monitoring-plugins pull request #1774
Opened 2022-07-02 15:44 UTC by archiecobbs

This causes a 255 exit value from ssh(1), which indicates a connection failure,
to return UNKNOWN instead of CRITICAL; similar to check_nrpe's "-u" flag.

2022-07-11 09:34 UTC, RincewindsHat commented
Resolves #1123 

Thank you very much for the PR.
I tried it and it seems, that it will change the behaviour only if `stderr` is ignored, since `ssh (1)` will output a message which will cause a `STATE_UNKNOWN` if `skip_stderr` is not present.
Seems like a valid use case anyway.
I would like one small change though, could you use to the `bool` type for the `unknown_timeout` variable to make the semantics more obvious?

2022-07-11 09:36 UTC, RincewindsHat requested changes

2022-07-11 09:36 UTC, RincewindsHat commented on plugins/check_by_ssh.c
> +int unknown_timeout = 0;
Please change the type to `bool` to make the semantics clearer

2022-07-11 15:41 UTC, archiecobbs commented
> it will change the behaviour only if stderr is ignored, since ssh (1) will output a message which will cause a STATE_UNKNOWN if skip_stderr is not present.

Not sure what you're talking about. The added patch happens on [line 105](https://github.com/archiecobbs/monitoring-plugins/blob/ca4b657381abdc760b8a54f74b8983877f506be9/plugins/check_by_ssh.c#L105) which is prior to [line 125](https://github.com/archiecobbs/monitoring-plugins/blob/ca4b657381abdc760b8a54f74b8983877f506be9/plugins/check_by_ssh.c#L125) where `skip_stderr` takes effect.

> I would like one small change though, could you use to the bool type for the unknown_timeout variable to make the semantics more obvious?

Good idea - thanks. Done.

2022-07-14 06:47 UTC, RincewindsHat approved these changes

2022-07-14 06:47 UTC, merged

2022-07-14 06:48 UTC, RincewindsHat commented
Looks good to me. Thank you very much