check_by_ssh: Add random wait option -r
monitoring-plugins/monitoring-plugins pull request #1817
Opened 2022-11-20 23:50 UTC by kompetenzbolzen

Added option -r, --random-wait=MAXTIME to wait for a random amount of seconds between 0 and MAXTIME.

This should help with deployments which check multiple services over SSH. I found that adding a wrapper to wait randomly for up to 10s reduced the amount of failed SSH connections dramatically, and thus eliminated many false alarms.

2022-11-30 00:00 UTC, sni commented
not sure if this is necessary to be builtin. Couldn't you simply do a `sleep $(($RANDOM%10)) && .../check_...`. Or even better, make use of ssh control master.
Ex.: like described here: https://labs.consol.de/nagios/omd/2012/06/12/running-check_by_ssh-over-a-persistent-ssh-connection.html

2022-11-30 00:12 UTC, kompetenzbolzen commented
I never tried ssh control master, thanks for the tip!
The original reason I built this was, that to wrap the check I needed to create a whole new check command, since I cant trivially overwrite the built-in one, which messed up the metric collection tagging based on the command name. 
I've seen this solution in some environments and I would think that adding a simple flag would be easier than wrapping the check.

2022-11-30 07:26 UTC, sni commented
ok, then my next question is why you use `dev/urandom` instead of `srand` and `random` from the stdlib. Ex.:
https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins-root/check_dhcp.c#L469

something like (untested):
```
srand(time(NULL));
sleep((random() % random_wait_max);
```

2022-11-30 12:31 UTC, kompetenzbolzen commented
Force of habit. There's no particular reason to use urandom here. I normally do because of its far better (at least afaik) randomness, but here thats ofc irrelevant. I'll change it to make it more uniform.

2023-09-07 14:40 UTC, RincewindsHat requested changes

2023-09-07 14:40 UTC, RincewindsHat commented on plugins/check_by_ssh.c
> +			if (!is_integer (optarg))
I guess this should be a test, whether this is a positive integer.

2024-10-31 00:43 UTC, RincewindsHat commented
Sorry for the long wait. I am gonna make a decision here.
I think it is not a good idea to add this as a feature in the plugin and therefore close this PR.
Scheduling checks is a problem of the monitoring system and bad SSH should be circumvented elsewhere.

2024-10-31 00:43 UTC, closed without merging