Fix for SSL host list messup when picking from multiple IPs (#1844)
monitoring-plugins/monitoring-plugins pull request #1847
Opened 2023-03-09 07:51 UTC by andreasbaumann

2023-03-11 10:33 UTC, RincewindsHat requested changes

2023-03-11 10:33 UTC, RincewindsHat commented on plugins/check_curl.c
> +  int s;
`s` is unused?

2023-03-11 10:40 UTC, andreasbaumann commented on plugins/check_curl.c
> +  int s;
Yep, removed in ea53555f

2023-03-12 09:59 UTC, merged

2023-03-12 10:00 UTC, RincewindsHat commented
Resolves #1844