fixed the outputs of the --versions options on 3 scripts
monitoring-plugins/monitoring-plugins pull request #1861
Opened 2023-04-11 14:28 UTC by MisterMountain

This fixes #1860

2023-04-11 14:58 UTC, RincewindsHat requested changes
Hi @MisterMountain,
Thanks very much. One small change would be welcome though.

2023-04-11 14:58 UTC, RincewindsHat commented on plugins-scripts/check_oracle.sh
> +    exit "$STATE_UNKNOWN"
While you are at it, could you fix the indentation here? :-)

2023-04-13 12:21 UTC, dermoth approved these changes
Looks good to me, I'll defer merging to active maintainers.

GH doesn't let me see the ws changes (i.e. tabs vs spaces) and typically I believe we used to standardize to tabs,, this appears to be using spaces. IMHO consistency within a single script is much more important so I have no concerns there.

2023-04-13 12:23 UTC, dermoth approved these changes

2023-04-13 12:24 UTC, RincewindsHat commented
@dermoth you really like that approve-button, don't you? :-)

2023-04-13 12:25 UTC, dermoth requested changes

2023-04-13 12:25 UTC, dermoth commented on plugins-scripts/check_oracle.sh
>      exit "$STATE_OK"
Actually I missed that (thought it was corrected in later commits)

Please fix

I haven't used GH for too long I guess.

2023-04-13 15:34 UTC, RincewindsHat commented
Actually since @MisterMountain mentioned, that the exit code for `help` and `version` should be `UNKNOWN` I was hoping, that the corresponding exit codes would also be fixed. This occured to me when I reviewed the changes. For example the exit code for `check_log` and `help` is `OK`

2023-04-14 07:56 UTC, MisterMountain commented
@RincewindsHat fixing the exit codes for help is still on my todolist :)

2023-05-02 07:41 UTC, MisterMountain commented
It took a while, but i did these changes - is there still something i forgot?

2023-05-02 08:33 UTC, RincewindsHat approved these changes
Looks good to me

2023-05-02 08:39 UTC, merged